#include "webserver_pages.h"

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "build_info.h"

void webserver_build_landing_page(char *buffer, size_t max_len, uint64_t frequency_hz,
                                  uint8_t drive_ma, const char *status_message, bool is_error) {
    if (!buffer || max_len == 0) {
        return;
    }

    const char *msg = (status_message && *status_message) ? status_message : NULL;
    const char *sel2 = (drive_ma == 2) ? " selected" : "";
    const char *sel4 = (drive_ma == 4) ? " selected" : "";
    const char *sel6 = (drive_ma == 6) ? " selected" : "";
    const char *sel8 = (drive_ma == 8) ? " selected" : "";

    char status_html[256] = {0};
    if (msg) {
        const char *status_class = is_error ? "status error" : "status ok";
        snprintf(status_html, sizeof(status_html),
                 "<div class=\"%s\"><span>%s</span></div>", status_class, msg);
    }

    const char *footer_text =
        "<span class=\"footer-line\">Configure the Si5351A output.</span>"
        "<span class=\"footer-line\">Frequency is applied to CLK0; drive strength maps to the chip's discrete 2/4/6/8 mA settings.</span>"
        "<span class=\"footer-meta\">Build " BUILD_GIT_COMMIT " &bull; " BUILD_COMPILED_AT "</span>";

    const char *default_status = "<div class=\"status ok\"><span>Clock generator ready</span></div>";

    snprintf(buffer, max_len,
             "<!DOCTYPE html>"
             "<html lang=\"en\">"
             "<head>"
             "<meta charset=\"utf-8\">"
             "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
             "<title>Clock Generator</title>"
             "<style>"
             "body{font-family:sans-serif;background:#f5f7fa;margin:0;}"
             ".page{display:flex;justify-content:center;align-items:flex-start;padding:2em;}"
             ".card{background:#fff;border-radius:12px;box-shadow:0 8px 24px rgba(15,23,42,0.15);padding:2em;max-width:460px;width:100%;}"
             ".card h1{text-align:center;margin:0;color:#1f2937;}"
             ".card form{display:flex;flex-direction:column;gap:1.1em;margin-top:1.2em;}"
             ".card label{display:flex;flex-direction:column;font-weight:600;color:#374151;gap:0.45em;}"
             ".card input,.card select{font-size:1em;padding:0.55em 0.7em;border:1px solid #d1d5db;border-radius:8px;box-shadow:inset 0 1px 2px rgba(0,0,0,0.05);}"
             ".digital{font-family:'DS-Digital','Segment7Standard','Courier New',monospace;letter-spacing:0.05em;background:#111827;color:#f9fafb;border-color:#1f2937;text-align:center;}"
             ".readout{display:flex;justify-content:center;align-items:center;font-size:1.2em;padding:0.75em;border:1px solid #1f2937;border-radius:8px;background:#111827;color:#f9fafb;box-shadow:inset 0 1px 3px rgba(0,0,0,0.25);}"
             ".step-group{display:flex;flex-wrap:wrap;gap:0.6em;}"
             ".step-option{display:flex;align-items:center;gap:0.35em;font-weight:500;font-size:0.95em;}"
             ".step-option input{width:auto;margin:0;}"
             ".status{margin-top:1em;padding:0.75em;border-radius:10px;border:1px solid #d1d5db;font-weight:600;text-align:center;}"
             ".status.ok{background:#e8f8ef;color:#1a6a2b;border-color:#9dd9a8;}"
             ".status.error{background:#fbeaea;color:#a32121;border-color:#f0a0a0;}"
             ".footer{text-align:center;margin-top:1.5em;font-size:0.9em;color:#4b5563;}"
             ".footer-line{display:block;}"
             ".footer-meta{display:block;margin-top:0.35em;font-size:0.75em;color:#6b7280;}"
             "@media (max-width:600px){.page{padding:1em;}.card{padding:1.5em;}}"
             "</style>"
             "<script>"
             "let submitTimer=null;"
             "function scheduleSubmit(){"
             "  if(submitTimer) clearTimeout(submitTimer);"
             "  submitTimer=setTimeout(function(){"
             "    const form=document.getElementById('signal-form');"
             "    if(form) form.requestSubmit();"
             "  },150);"
             "}"
             "window.addEventListener('DOMContentLoaded',function(){"
             "  const spinner=document.getElementById('frequency-spinner');"
             "  let suppressSubmit=false;"
             "  let manualEdit=false;"
             "  const display=document.getElementById('frequency-display');"
             "  const formatWithSeparators=function(value){"
             "    if(value===undefined||value===null) return '';"
             "    const digits=String(value).replace(/[^0-9]/g,'');"
             "    if(!digits.length) return '';"
             "    return digits.replace(/\\B(?=(\\d{3})+(?!\\d))/g,'.');"
             "  };"
             "  const syncDisplay=function(){"
             "    if(display&&spinner){"
             "      display.textContent=formatWithSeparators(spinner.value);"
             "    }"
             "  };"
             "  const updateStep=function(stepValue){"
             "    if(!spinner) return;"
             "    const numeric=parseInt(stepValue,10);"
             "    if(numeric>=1){"
             "      spinner.step=numeric;"
             "    }"
             "  };"
             "  if(spinner){"
             "    spinner.addEventListener('focus',function(){"
             "      manualEdit=false;"
             "      if(!suppressSubmit){"
             "        syncDisplay();"
             "      }"
             "    });"
             "    spinner.addEventListener('pointerdown',function(){"
             "      manualEdit=false;"
             "      suppressSubmit=false;"
             "    });"
             "    spinner.addEventListener('keydown',function(event){"
             "      if(event.key==='Enter'){"
             "        event.preventDefault();"
             "        manualEdit=false;"
             "        suppressSubmit=false;"
             "        syncDisplay();"
             "        scheduleSubmit();"
             "        return;"
             "      }"
             "      const manualKeys=['Backspace','Delete'];"
             "      const isDigit=event.key.length===1 && event.key>='0' && event.key<='9';"
             "      if(isDigit || manualKeys.indexOf(event.key)!==-1){"
             "        manualEdit=true;"
             "        suppressSubmit=true;"
             "      }"
             "    });"
             "    spinner.addEventListener('input',function(){"
             "      syncDisplay();"
             "      if(!suppressSubmit){"
             "        scheduleSubmit();"
             "      }"
             "    });"
             "    spinner.addEventListener('change',function(){"
             "      syncDisplay();"
             "      suppressSubmit=false;"
             "      manualEdit=false;"
             "      scheduleSubmit();"
             "    });"
             "    spinner.addEventListener('blur',function(){"
             "      if(manualEdit){"
             "        manualEdit=false;"
             "        suppressSubmit=false;"
             "        syncDisplay();"
             "        scheduleSubmit();"
             "      }"
             "    });"
             "    spinner.addEventListener('wheel',function(event){event.preventDefault();},{passive:false});"
             "    syncDisplay();"
             "  }"
             "  const stepRadios=document.querySelectorAll('input[name=\"step\"]');"
             "  if(stepRadios.length){"
             "    const savedStep=window.localStorage?localStorage.getItem('clockgen-step'):null;"
             "    let selectedValue=null;"
             "    stepRadios.forEach(function(radio){"
             "      if(savedStep && radio.value===savedStep){"
             "        radio.checked=true;"
             "        selectedValue=radio.value;"
             "      } else if(radio.checked && !selectedValue){"
             "        selectedValue=radio.value;"
             "      }"
             "    });"
             "    if(selectedValue){"
             "      updateStep(selectedValue);"
             "    } else if(spinner){"
             "      updateStep(spinner.step || '1000');"
             "    }"
             "    stepRadios.forEach(function(radio){"
             "      radio.addEventListener('change',function(){"
             "        if(radio.checked){"
             "          updateStep(radio.value);"
             "          if(window.localStorage){"
             "            localStorage.setItem('clockgen-step', radio.value);"
             "          }"
             "        }"
             "      });"
             "    });"
             "  }"
             "});"
             "</script>"
             "</head>"
             "<body>"
             "<div class=\"page\"><div class=\"card\">"
             "<h1>Clock Generator</h1>"
             "%s"
             "<form id=\"signal-form\" method=\"POST\" action=\"/signal\">"
             "<label>Frequency (Hz)"
             "<div id=\"frequency-display\" class=\"readout digital\" role=\"status\" aria-live=\"polite\">%llu</div>"
             "</label>"
             "<label>Adjust"
             "<input type=\"number\" name=\"frequency\" id=\"frequency-spinner\" class=\"digital\" min=\"8000\" max=\"200000000\" step=\"1000\" value=\"%llu\">"
             "</label>"
             "<label>Increment"
             "<div class=\"step-group\">"
             "<label class=\"step-option\"><input type=\"radio\" name=\"step\" value=\"1\">1 Hz</label>"
             "<label class=\"step-option\"><input type=\"radio\" name=\"step\" value=\"10\">10 Hz</label>"
             "<label class=\"step-option\"><input type=\"radio\" name=\"step\" value=\"100\">100 Hz</label>"
             "<label class=\"step-option\"><input type=\"radio\" name=\"step\" value=\"1000\" checked>1 kHz</label>"
             "<label class=\"step-option\"><input type=\"radio\" name=\"step\" value=\"10000\">10 kHz</label>"
             "<label class=\"step-option\"><input type=\"radio\" name=\"step\" value=\"100000\">100 kHz</label>"
             "<label class=\"step-option\"><input type=\"radio\" name=\"step\" value=\"1000000\">1 MHz</label>"
             "<label class=\"step-option\"><input type=\"radio\" name=\"step\" value=\"10000000\">10 MHz</label>"
             "</div>"
             "</label>"
             "<label>Drive strength"
             "<select name=\"drive\" onchange=\"scheduleSubmit()\">"
             "<option value=\"2\"%s>2 mA</option>"
             "<option value=\"4\"%s>4 mA</option>"
             "<option value=\"6\"%s>6 mA</option>"
             "<option value=\"8\"%s>8 mA</option>"
             "</select>"
             "</label>"
             "</form>"
             "<div class=\"footer\">%s</div>"
             "</div></div>"
             "</body>"
             "</html>",
             status_html[0] ? status_html : default_status,
             (unsigned long long)frequency_hz,
             (unsigned long long)frequency_hz,
             sel2, sel4, sel6, sel8,
             footer_text);
}
